package bean;
// Generated 15/09/2023 09:27:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RsLogin generated by hbm2java
 */
@Entity
@Table(name="rs_login"
    ,catalog="db_rafael_schneider"
)
public class RsLogin  implements java.io.Serializable {


     private int rsIdlogin;
     private String rsApelido;
     private String rsSenha;

    public RsLogin() {
    }

    public RsLogin(int rsIdlogin, String rsApelido, String rsSenha) {
       this.rsIdlogin = rsIdlogin;
       this.rsApelido = rsApelido;
       this.rsSenha = rsSenha;
    }
   
     @Id 

    
    @Column(name="rs_idlogin", unique=true, nullable=false)
    public int getRsIdlogin() {
        return this.rsIdlogin;
    }
    
    public void setRsIdlogin(int rsIdlogin) {
        this.rsIdlogin = rsIdlogin;
    }

    
    @Column(name="rs_apelido", nullable=false, length=45)
    public String getRsApelido() {
        return this.rsApelido;
    }
    
    public void setRsApelido(String rsApelido) {
        this.rsApelido = rsApelido;
    }

    
    @Column(name="rs_senha", nullable=false, length=45)
    public String getRsSenha() {
        return this.rsSenha;
    }
    
    public void setRsSenha(String rsSenha) {
        this.rsSenha = rsSenha;
    }




}


