package bean;
// Generated 30/11/2023 17:41:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RsProduto generated by hbm2java
 */
@Entity
@Table(name="rs_Produto"
    ,catalog="db_rafael_schneider"
)
public class RsProduto  implements java.io.Serializable {


     private int rsIdProduto;
     private String rsSabor;
     private int rsCopoOuCasquinha;
     private int rsTamanho;
     private Set rsVendaProdutos = new HashSet(0);

    public RsProduto() {
    }

	
    public RsProduto(int rsIdProduto, String rsSabor, int rsCopoOuCasquinha, int rsTamanho) {
        this.rsIdProduto = rsIdProduto;
        this.rsSabor = rsSabor;
        this.rsCopoOuCasquinha = rsCopoOuCasquinha;
        this.rsTamanho = rsTamanho;
    }
    public RsProduto(int rsIdProduto, String rsSabor, int rsCopoOuCasquinha, int rsTamanho, Set rsVendaProdutos) {
       this.rsIdProduto = rsIdProduto;
       this.rsSabor = rsSabor;
       this.rsCopoOuCasquinha = rsCopoOuCasquinha;
       this.rsTamanho = rsTamanho;
       this.rsVendaProdutos = rsVendaProdutos;
    }
   
     @Id 

    
    @Column(name="rs_idProduto", unique=true, nullable=false)
    public int getRsIdProduto() {
        return this.rsIdProduto;
    }
    
    public void setRsIdProduto(int rsIdProduto) {
        this.rsIdProduto = rsIdProduto;
    }

    
    @Column(name="rs_sabor", nullable=false, length=100)
    public String getRsSabor() {
        return this.rsSabor;
    }
    
    public void setRsSabor(String rsSabor) {
        this.rsSabor = rsSabor;
    }

    
    @Column(name="rs_copo_ou_casquinha", nullable=false)
    public int getRsCopoOuCasquinha() {
        return this.rsCopoOuCasquinha;
    }
    
    public void setRsCopoOuCasquinha(int rsCopoOuCasquinha) {
        this.rsCopoOuCasquinha = rsCopoOuCasquinha;
    }

    
    @Column(name="rs_tamanho", nullable=false)
    public int getRsTamanho() {
        return this.rsTamanho;
    }
    
    public void setRsTamanho(int rsTamanho) {
        this.rsTamanho = rsTamanho;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rsProduto")
    public Set getRsVendaProdutos() {
        return this.rsVendaProdutos;
    }
    
    public void setRsVendaProdutos(Set rsVendaProdutos) {
        this.rsVendaProdutos = rsVendaProdutos;
    }




}


