package bean;
// Generated 15/09/2023 09:27:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RsProduto generated by hbm2java
 */
@Entity
@Table(name="rs_Produto"
    ,catalog="db_rafael_schneider"
)
public class RsProduto  implements java.io.Serializable {


     private int rsIdProduto;
     private String rsSabor;
     private int rsCopoOuCasquinha;
     private int rsTamanho;

    public RsProduto() {
    }

    public RsProduto(int rsIdProduto, String rsSabor, int rsCopoOuCasquinha, int rsTamanho) {
       this.rsIdProduto = rsIdProduto;
       this.rsSabor = rsSabor;
       this.rsCopoOuCasquinha = rsCopoOuCasquinha;
       this.rsTamanho = rsTamanho;
    }
   
     @Id 

    
    @Column(name="rs_idProduto", unique=true, nullable=false)
    public int getRsIdProduto() {
        return this.rsIdProduto;
    }
    
    public void setRsIdProduto(int rsIdProduto) {
        this.rsIdProduto = rsIdProduto;
    }

    
    @Column(name="rs_sabor", nullable=false, length=45)
    public String getRsSabor() {
        return this.rsSabor;
    }
    
    public void setRsSabor(String rsSabor) {
        this.rsSabor = rsSabor;
    }

    
    @Column(name="rs_copo_ou_casquinha", nullable=false)
    public int getRsCopoOuCasquinha() {
        return this.rsCopoOuCasquinha;
    }
    
    public void setRsCopoOuCasquinha(int rsCopoOuCasquinha) {
        this.rsCopoOuCasquinha = rsCopoOuCasquinha;
    }

    
    @Column(name="rs_tamanho", nullable=false)
    public int getRsTamanho() {
        return this.rsTamanho;
    }
    
    public void setRsTamanho(int rsTamanho) {
        this.rsTamanho = rsTamanho;
    }




}


