package bean;
// Generated 30/11/2023 17:41:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RsVendaProduto generated by hbm2java
 */
@Entity
@Table(name="rs_venda_produto"
    ,catalog="db_rafael_schneider"
)
public class RsVendaProduto  implements java.io.Serializable {


     private int rsIdvendaProduto;
     private RsProduto rsProduto;
     private RsVenda rsVenda;

    public RsVendaProduto() {
    }

    public RsVendaProduto(int rsIdvendaProduto, RsProduto rsProduto, RsVenda rsVenda) {
       this.rsIdvendaProduto = rsIdvendaProduto;
       this.rsProduto = rsProduto;
       this.rsVenda = rsVenda;
    }
   
     @Id 

    
    @Column(name="rs_idvenda_produto", unique=true, nullable=false)
    public int getRsIdvendaProduto() {
        return this.rsIdvendaProduto;
    }
    
    public void setRsIdvendaProduto(int rsIdvendaProduto) {
        this.rsIdvendaProduto = rsIdvendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rs_idProduto", nullable=false)
    public RsProduto getRsProduto() {
        return this.rsProduto;
    }
    
    public void setRsProduto(RsProduto rsProduto) {
        this.rsProduto = rsProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rs_idvenda", nullable=false)
    public RsVenda getRsVenda() {
        return this.rsVenda;
    }
    
    public void setRsVenda(RsVenda rsVenda) {
        this.rsVenda = rsVenda;
    }




}


