package bean;
// Generated 20/10/2023 17:25:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RsVendaProduto generated by hbm2java
 */
@Entity
@Table(name="rs_venda_produto"
    ,catalog="db_rafael_schneider"
)
public class RsVendaProduto  implements java.io.Serializable {


     private int rsIdvendaProduto;

    public RsVendaProduto() {
    }

    public RsVendaProduto(int rsIdvendaProduto) {
       this.rsIdvendaProduto = rsIdvendaProduto;
    }
   
     @Id 

    
    @Column(name="rs_idvenda_produto", unique=true, nullable=false)
    public int getRsIdvendaProduto() {
        return this.rsIdvendaProduto;
    }
    
    public void setRsIdvendaProduto(int rsIdvendaProduto) {
        this.rsIdvendaProduto = rsIdvendaProduto;
    }




}


