package bean;
// Generated 30/11/2023 17:41:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RsVendedor generated by hbm2java
 */
@Entity
@Table(name="rs_vendedor"
    ,catalog="db_rafael_schneider"
)
public class RsVendedor  implements java.io.Serializable {


     private int rsIdvendedor;
     private String rsNome;
     private String rsSobrenome;
     private String rsCpf;
     private Date rsDataNascimento;
     private String rsTelefone;
     private String rsLogin;
     private int rsFuncao;
     private Set rsVendas = new HashSet(0);

    public RsVendedor() {
    }

	
    public RsVendedor(int rsIdvendedor, String rsNome, String rsSobrenome, String rsCpf, Date rsDataNascimento, String rsTelefone, String rsLogin, int rsFuncao) {
        this.rsIdvendedor = rsIdvendedor;
        this.rsNome = rsNome;
        this.rsSobrenome = rsSobrenome;
        this.rsCpf = rsCpf;
        this.rsDataNascimento = rsDataNascimento;
        this.rsTelefone = rsTelefone;
        this.rsLogin = rsLogin;
        this.rsFuncao = rsFuncao;
    }
    public RsVendedor(int rsIdvendedor, String rsNome, String rsSobrenome, String rsCpf, Date rsDataNascimento, String rsTelefone, String rsLogin, int rsFuncao, Set rsVendas) {
       this.rsIdvendedor = rsIdvendedor;
       this.rsNome = rsNome;
       this.rsSobrenome = rsSobrenome;
       this.rsCpf = rsCpf;
       this.rsDataNascimento = rsDataNascimento;
       this.rsTelefone = rsTelefone;
       this.rsLogin = rsLogin;
       this.rsFuncao = rsFuncao;
       this.rsVendas = rsVendas;
    }
   
     @Id 

    
    @Column(name="rs_idvendedor", unique=true, nullable=false)
    public int getRsIdvendedor() {
        return this.rsIdvendedor;
    }
    
    public void setRsIdvendedor(int rsIdvendedor) {
        this.rsIdvendedor = rsIdvendedor;
    }

    
    @Column(name="rs_nome", nullable=false, length=100)
    public String getRsNome() {
        return this.rsNome;
    }
    
    public void setRsNome(String rsNome) {
        this.rsNome = rsNome;
    }

    
    @Column(name="rs_sobrenome", nullable=false, length=100)
    public String getRsSobrenome() {
        return this.rsSobrenome;
    }
    
    public void setRsSobrenome(String rsSobrenome) {
        this.rsSobrenome = rsSobrenome;
    }

    
    @Column(name="rs_cpf", nullable=false, length=15)
    public String getRsCpf() {
        return this.rsCpf;
    }
    
    public void setRsCpf(String rsCpf) {
        this.rsCpf = rsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rs_dataNascimento", nullable=false, length=10)
    public Date getRsDataNascimento() {
        return this.rsDataNascimento;
    }
    
    public void setRsDataNascimento(Date rsDataNascimento) {
        this.rsDataNascimento = rsDataNascimento;
    }

    
    @Column(name="rs_telefone", nullable=false, length=15)
    public String getRsTelefone() {
        return this.rsTelefone;
    }
    
    public void setRsTelefone(String rsTelefone) {
        this.rsTelefone = rsTelefone;
    }

    
    @Column(name="rs_login", nullable=false, length=100)
    public String getRsLogin() {
        return this.rsLogin;
    }
    
    public void setRsLogin(String rsLogin) {
        this.rsLogin = rsLogin;
    }

    
    @Column(name="rs_funcao", nullable=false)
    public int getRsFuncao() {
        return this.rsFuncao;
    }
    
    public void setRsFuncao(int rsFuncao) {
        this.rsFuncao = rsFuncao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rsVendedor")
    public Set getRsVendas() {
        return this.rsVendas;
    }
    
    public void setRsVendas(Set rsVendas) {
        this.rsVendas = rsVendas;
    }




}


