package bean;
// Generated 20/10/2023 17:25:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RsVenda generated by hbm2java
 */
@Entity
@Table(name="rs_venda"
    ,catalog="db_rafael_schneider"
)
public class RsVenda  implements java.io.Serializable {


     private int rsIdvenda;
     private int rsTotal;
     private String rsFormaPagamento;
     private String rsVendedor;

    public RsVenda() {
    }

    public RsVenda(int rsIdvenda, int rsTotal, String rsFormaPagamento, String rsVendedor) {
       this.rsIdvenda = rsIdvenda;
       this.rsTotal = rsTotal;
       this.rsFormaPagamento = rsFormaPagamento;
       this.rsVendedor = rsVendedor;
    }
   
     @Id 

    
    @Column(name="rs_idvenda", unique=true, nullable=false)
    public int getRsIdvenda() {
        return this.rsIdvenda;
    }
    
    public void setRsIdvenda(int rsIdvenda) {
        this.rsIdvenda = rsIdvenda;
    }

    
    @Column(name="rs_total", nullable=false)
    public int getRsTotal() {
        return this.rsTotal;
    }
    
    public void setRsTotal(int rsTotal) {
        this.rsTotal = rsTotal;
    }

    
    @Column(name="rs_forma_pagamento", nullable=false, length=3)
    public String getRsFormaPagamento() {
        return this.rsFormaPagamento;
    }
    
    public void setRsFormaPagamento(String rsFormaPagamento) {
        this.rsFormaPagamento = rsFormaPagamento;
    }

    
    @Column(name="rs_vendedor", nullable=false, length=45)
    public String getRsVendedor() {
        return this.rsVendedor;
    }
    
    public void setRsVendedor(String rsVendedor) {
        this.rsVendedor = rsVendedor;
    }




}


